### ISSUE TITLE
SmartView 4K - Input select

### ISSUE THREAD

**Issue by Phantomet** [bitfocus/companion-module-bmd-smartview#1]
**Describe the feature**
A clear and concise description of what the feature does
I like to be able to switch the input between  A or B og hopefulle select it direct.

**Is this platform dependent (windows, mac, ..)?**
Explain

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
Add a couple of usecases for why this should be implemented and when/why to use it.

**Comment by krocheck** [comment]
@Phantomet finally getting around to this.  But I don't own one of these and BMD didn't document in the manual a way to switch the input on this monitor (as nothing else in the line has multiple inputs).  In order to make this happen I will likely need to you telnet into the unit and run a help command to see if it lists a command for this.  Are able to do this?

**Comment by JeffreyDavidsz** [comment]
`Monitor A:`
`<CR>`
`MonitorInput: SDI B`
`<CR>`
`<CR>`

For selecting SDI B as input

**Comment by krocheck** [comment]
Awesome! Can you check if the optical input is addressed as `OPTICAL` or `Optical`?

**Comment by JeffreyDavidsz** [comment]
@krocheck someone posted this on Facebook, just putting it here so we won't forget

**Comment by krocheck** [comment]
gotcha

**Comment by krocheck** [comment]
@Phantomet the current beta build has this input selection added.  If you have an opportunity to test, please report back here.

**Comment by RoseOO** [comment]
@krocheck I have a SmartView 4K now and I was just looking for an input select option. Doesn't seem to be an action that is available at the moment and I'm on the latest commit. Don't mind having a look at doing a PR myself if it needs updating or something.

EDIT: Nevermind the type selection hadn't saved the first time round, I'll test it out

**Comment by RoseOO** [comment]
This works, the feedback would switch to optical briefly when I selected it but switches back to SDI A because I don't have a fibre SDI module
