### ISSUE TITLE
v3.0 Smartview Duo 4k 

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-bmd-smartview#12]
Configured buttons do not work. Debug log shows `debug: Socket not connected :(`
Same buttons work in v2.4.2

**Comment by josephdadams** [comment]
@krocheck i think it’s the check for socket.connected, if you use TCPHelper class, you use isConnected

**Comment by thommoser** [comment]
@josephdadams I've the same problem... but I don't understand how I can solve it with your answer... could you give me bit more explanation about it? =) thx

**Comment by josephdadams** [comment]
Bug in the module code
