### ISSUE TITLE
Instance feedback: SmartScope / SmartView Tally Borders

### ISSUE THREAD

**Issue by Sam-D03** [bitfocus/companion-module-bmd-smartview#2]
**Describe the feature**
The ability to OUTPUT instant feedback of an action (ATEM source on Program, ATEM source on Preview etc) results in triggering of the tally border of SmartScope / SmartView monitor.

**Is this platform dependent (windows, mac, ..)?**
Not platform dependent. SmartView module can already send tally commands to monitors.

**If documentation is required to implement, do you know where to find it?**
If applicable, add screenshots, protocol description PDFs, etc to help the developers along

**Usecases**
PTZ Operator has a stack of SmartView monitors with their cameras on, one camera per smart view. PTZ camera 1 goes live, a border around SmartView monitor 1 appears to let the operator know that source is live on PGM.

**Comment by krocheck** [comment]
@Sam-D03 the current beta build has feedback added.  If you have ability to test, that would be helpful.  I know that isn't 100% of what you were requesting here, but its definitely a component to eventually getting all the way there.

**Comment by daniep01** [comment]
I'm testing the feedback feature on a SmartScope Duo 4K and not seeing any update to the button backgrounds when I change scope modes (picture/rgb/vector).

**Comment by RoseOO** [comment]
This works with feedback on the SmartView 4K

**Comment by daniep01** [comment]
It now works for me too, not sure exactly when it was resolved.
